package javaTest;

import java.io.IOException;

public class expetest {
	public static void main(String[] args) throws IOException {
		
	
try {
	int a=5, b=0;

	int c=a/b;
}
catch (Exception e) {
	
}
System.out.println("hi all friend");	}// TODO: handle exception
}

